In [5]:
import pandas as pd
import numpy as np
data = np.array(pd.read_csv('FPL_database_new.csv'))
print(data)

[[1 'Leno' 4.6 1 0 0.0]
 [1 'Rúnarsson' 4.0 1 0 0.0]
 [3 'Willian' 6.3 1 0 0.0]
 ...
 [2 'McQueen' 99.9 17 0 0.0]
 [4 'Kayky' 99.9 4 0 0.0]
 [4 'Kayky' 99.9 4 0 0.0]]


In [23]:
new_data = np.zeros((645,6))
count = np.zeros((20,4))
ES = np.zeros((20,4))
c = np.zeros((20,4))
for i in range(645):
    for j in range(1,21):
        for k in range(1,5):
            if(data[i,3] == j and data[i,0] == k and data[i,4] !=0):
                count[j-1,k-1] = count[j-1,k-1] + 1
                ES[j-1,k-1] = (ES[j-1,k-1] + (data[i,5]*90)/data[i,4])
                c[j-1,k-1] = (c[j-1,k-1] + data[i,2])
ES = ES/count
c = c/count
print(count)                
print(ES)
print(c)
np.savetxt('Exp_Score.csv',ES)
np.savetxt('Cost.csv',c)

[[ 1.  6.  9.  2.]
 [ 2.  7.  8.  4.]
 [ 2.  7.  8.  2.]
 [ 1.  7.  9.  1.]
 [ 2.  7.  8.  3.]
 [ 1. 10. 11.  2.]
 [ 1.  7.  7.  4.]
 [ 1.  8. 11.  2.]
 [ 1.  7. 10.  1.]
 [ 1.  7.  9.  3.]
 [ 1.  8.  9.  3.]
 [ 1.  7.  9.  3.]
 [ 1.  6. 11.  2.]
 [ 1.  8.  9.  3.]
 [ 1.  6. 10.  1.]
 [ 1.  8.  9.  2.]
 [ 1.  6. 10.  3.]
 [ 1.  7.  8.  1.]
 [ 1.  8.  6.  4.]
 [ 1.  8.  6.  3.]]
[[3.24303371 1.84039657 3.55088686 3.90547561]
 [3.69931034 3.21839201 3.81537327 4.83505564]
 [3.7911236  3.19623883 3.98988995 4.68578571]
 [4.64966292 5.28887391 6.18053375 5.67875   ]
 [3.65826429 3.37983164 3.84547577 4.97225735]
 [3.69       3.48567755 4.11369827 5.19105882]
 [3.67179775 3.3888454  3.55256337 5.16501623]
 [4.06329545 4.35384436 4.75824871 5.27613158]
 [3.70617978 3.45497396 4.20773224 4.54714286]
 [3.83359551 3.23914234 4.1845991  4.52039839]
 [3.43314607 2.79636895 3.80892971 4.45067616]
 [3.17022472 1.65219198 2.98960775 3.5864759 ]
 [3.34314607 2.46054443 3.49446604 4.20335526]
 [3.3633